version: "3.9"
services:
  hardhat:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./hardhat:/app
    command: >
      sh -c "npx hardhat node & 
      sleep 5 && 
      yarn compile &&
      yarn test &&
      yarn deploy --network localhost && 
      tail -f /dev/null"
    ports:
      - "8545:8545"

  ipfs:
    image: ipfs/kubo:latest
    command: daemon --init --migrate=true --api=/ip4/0.0.0.0/tcp/5001 --routing=dhtclient
    ports:
      - "5001:5001" # IPFS API
      - "8080:8080" # IPFS Gateway

  api:
    build: ./api
    depends_on:
      - hardhat
      - ipfs
    ports:
      - "8000:8000"
    command: ["./api"]
    environment:
        - IPFS_URL=ipfs:5001
        - PORT=8000
        - ETH_RPC_URL=http://hardhat:8545
        - CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
        - CHAIN_ID=31337
        - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    volumes:
      - ./api/contracts/file_registry.abi:/app/contracts/file_registry.abi


